language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip

services:
  - docker

before_install:
  - docker pull mysql:5.7
  - docker run -d -p 127.0.0.1:3307:3306 --name mysqld -e MYSQL_DATABASE=gorm -e MYSQL_USER=gorm -e MYSQL_PASSWORD=gorm -e MYSQL_ROOT_PASSWORD=verysecret
    mysql:5.7 --innodb_log_file_size=256MB --innodb_buffer_pool_size=512MB --max_allowed_packet=16MB
  - sleep 30
  - cp .travis/docker.cnf ~/.my.cnf
  - mysql --print-defaults
  - .travis/wait_mysql.sh

before_script:
  - mysql -e 'CREATE DATABASE gorm;'
  - mysql -e 'GRANT ALL ON gorm.* TO gorm@localhost';

script:
  - GORM_DIALECT="mysql" go test -v